gracefully handle case where transmission is not running

diff --git a/bin/transmission-watchdog b/bin/transmission-watchdog
--- a/bin/transmission-watchdog
+++ b/bin/transmission-watchdog
@@ -72,9 +72,18 @@ timeout () {
 }
 
 remote () {
-    # TODO: catch "Couldn't connect to server" error and exit
     # TODO: add retry and kill logic
-    timeout 30 transmission-remote -N $NETRC "$@"
+    exec 3>&1 4>&2
+    if ! error=$(
+        { timeout 30 transmission-remote -N $NETRC "$@" 2>&4 1>&3; } 4>&1
+    ); then
+        case $error in
+            *"Couldn't connect to server")
+                warn "$error\n"
+                exit 1
+        esac
+    fi
+    exec 3>&- 4>&-
 }
 
 real_dir () {
