add functionality:     - verify RAR archives with cksfv     - unrar RAR archives     - remove RAR archives if unrar is successful and after torrent       stops

diff --git a/bin/transmission-watchdog b/bin/transmission-watchdog
--- a/bin/transmission-watchdog
+++ b/bin/transmission-watchdog
@@ -4,16 +4,19 @@
 #   - finds torrents under a directory (including its subdirectories) and
 #     adds them to transmission, specifying the directory from where the
 #     torrent was located to be the completed directory for the data
+#   - throttles public torrents
 #   - removes completed, stopped torrents
 #   - removes idle, expired torrents
-#   - changes upload rate and ratio for public torrents
+#   - verifies RAR archives with cksfv
+#   - unrars RAR archives
+#   - removes RAR archives after torrent has been removed
 #
 # TODO:
-#   - unrars RAR archives
-#   - kills transmission if it's hanging so it can be restarted by some
+#   - make idle expiration test portable- don't rely on gnu date
+#   - kill transmission if it's hanging so it can be restarted by some
 #     external process (launchd, inetd, etc.)
 
-VERBOSE=0
+VERBOSE=1
 LOCK=/tmp/transmission-watchdog.lock
 NETRC=~/.netrc
 WATCH_DIR=~/Media/.
@@ -22,34 +25,28 @@ IDLE_EXPIRED_HOURS=24
 PUBLIC_UP_RATE=5
 PUBLIC_RATIO=0
 
-[ 1 != "$CRON" ] && VERBOSE=1
-
 set -e
 
-if ! command -v transmission-remote >/dev/null 2>&1; then
-    echo "Can't find transmission-remote" >&2
-    exit 1
-fi
+has_cmd () { command -v "$@" >/dev/null 2>&1; }
+warn    () { printf "$@" >&2; }
 
-if command -v flock >/dev/null 2>&1; then
+if has_cmd flock; then
     flock -nx "$LOCK" || exit
-elif command -v shlock >/dev/null 2>&1; then
+elif has_cmd shlock; then
     trap 'rm -f "$LOCK"; exit' HUP INT QUIT TERM
     shlock -f "$LOCK" -p $$ || exit
     trap 'rm -f "$LOCK"; exit' EXIT
-elif command -v lockfile >/dev/null 2>&1; then
+elif has_cmd lockfile; then
     trap 'rm -f "$LOCK"; exit' HUP INT QUIT TERM
     lockfile -r 0 -l 300 "$LOCK" >/dev/null 2>&1 || exit
     trap 'rm -f "$LOCK"; exit' EXIT
 else
-    echo "Put a leash on the watchdog- install flock, shlock or lockfile" >&2
+    warn "Running without a lock- install flock, shlock or lockfile\n"
 fi
 
 # Prefer the timeout program from GNU coreutils.
-if command -v timeout >/dev/null 2>&1; then
-    :
-elif command -v gtimeout >/dev/null 2>&1; then
-    timeout () { gtimeout "$@"; }
+if   has_cmd timeout;  then :
+elif has_cmd gtimeout; then timeout () { gtimeout "$@"; }
 else
     # From "Beginning Portable Shell Scripting", 2008.
     timeout () {
@@ -80,8 +77,7 @@ transmit () {
 }
 
 # Add any new torrent files to transmission, then archive them.
-find "$WATCH_DIR" -type f -name '*.torrent' | \
-while IFS= read -r file; do
+find "$WATCH_DIR" -type f -name '*.torrent' | while IFS= read -r file; do
     dir=${file%/*}
 
     # transmission-remote doesn't yet allow setting the directory for only
@@ -92,64 +88,112 @@ while IFS= read -r file; do
     transmit --download-dir "$WATCH_DIR" >/dev/null 2>&1
 
     mv -f "$file" "$ARCHIVE_DIR"
+
+    [ 1 = "$VERBOSE" ] && printf "Added torrent: ${file##*/}\n"
 done
 
 # TODO: make this portable.
-is_idle_expired () {
+is_expired () {
     [ -z "$1" ] && return 1
+
+    _expired=$(($IDLE_EXPIRED_HOURS * 3600))
     _now=$(gdate +%s)
-    _last=$(gdate --date "$1" +%s)
-    [ $(($_now - $_last)) -lt $(($IDLE_EXPIRED_HOURS * 3600)) ] && return 1
+    _started=$(gdate --date "$1" +%s)
+    if [ -n "$2" ]; then
+        _last_active=$(gdate --date "$2" +%s)
+    else
+        _last_active=0
+    fi
+
+    [ $(($_now - $_started))     -gt $_expired ] &&
+    [ $(($_now - $_last_active)) -gt $_expired ] &&
+    return 1
 }
 
-transmit --torrent all --info | \
-while IFS= read -r line; do
+has_cmd unrar && HAS_UNRAR=1
+has_cmd cksfv && HAS_CKSFV=1
+
+transmit --torrent all --info | while IFS= read -r line; do
     val=${line##*: }
     case $line in
-        'Id: '?*)              id=$val          ;;
-        'Name: '?*)            name=$val        ;;
-        'State: '?*)           state=$val       ;;
-        'Location: '?*)        dir=$val         ;;
-        'Percent Done: '?*)    percent=$val     ;;
-        'Latest activity: '?*) last_active=$val ;;
-        'Public torrent: '?*)  public=$val      ;;
-        'Upload Limit: '?*)    up_rate=$val
-                               do=1             ;;
+        '  Id: '?*)              id=$val          ;;
+        '  Name: '?*)            name=$val        ;;
+        '  State: '?*)           state=$val       ;;
+        '  Location: '?*)        dir=$val         ;;
+        '  Percent Done: '?*)    percent=$val     ;;
+        '  Date started: '?*)    started=$val     ;;
+        '  Latest activity: '?*) last_active=$val ;;
+        '  Public torrent: '?*)  public=$val      ;;
+        '  Upload Limit: '?*)    up_rate=$val
+                                 do=1             ;;
     esac
 
     [ 1 != "$do" ] && continue; do=0
 
+    unset last_dir removed unrarred_lock unrarred
+
     if [ '100%' = "$percent" ]; then
-        if [ 'Idle' = "$state" ]; then
-            # Determine if torrent has expired due to inactivity.
-            if is_idle_expired "$last_active"; then
-                transmit --torrent "$id" --remove >/dev/null 2>&1
-                [ 1 = "$VERBOSE" ] && echo "Stopping idle torrent: $name"
-            fi
-        elif [ 'Stopped' = "$state" ]; then
-            # Remove completed and stopped torrents.
+        if [ 1 = "$HAS_UNRAR" ]; then
+            find "$dir/$name" -type f -name '*.rar' | \
+            while IFS= read -r file; do
+                rar_dir=${file%/*}
+                rar_file=${file##*/}
+                [ "$rar_dir" = "$last_dir" ] && continue
+                last_dir=$rar_dir
+                unrarred_lock="$rar_dir/.$rar_file.unrarred"
+                [ -e "$unrarred_lock" ] && continue
+
+                sfv_file="${rar_file%.*}".sfv
+                if [ 1 = "$HAS_CKSFV" ] && [ -e "$sfv_file" ]; then
+                    if ! nice -n 15 cksfv -vg "$rar_dir/$sfv_file"; then
+                        touch "$unrarred_lock"
+                        if [ 1 = "$VERBOSE" ]; then
+                            warn "Invalid RAR: ${rar_dir##~/}/$rar_file\n"
+                        fi
+                        continue
+                    fi
+                fi
+
+                touch "$unrarred_lock"
+
+                if ! nice -n 15 unrar x -inul -y -p- -o+ -r \
+                        "$rar_dir/$rar_file" "$rar_dir"
+                then
+                    warn "Unable to extract RAR: ${rar_dir##~/}/$rar_file\n"
+                    continue
+                fi
+
+                unrarred=1
+
+                if [ 1 = "$VERBOSE" ]; then
+                    printf "Unrarred %s/%s\n" "${rar_dir##~/}" "$rar_file"
+                fi
+            done
+        fi
+
+        if [ 'Idle' = "$state" ] && is_expired "$started" "$last_active"
+        then
             transmit --torrent "$id" --remove >/dev/null 2>&1
-            [ 1 = "$VERBOSE" ] && echo "Removed completed torrent: $name"
-
-            # TODO: Unrar any RAR archives.
-            # if command -v unrar >/dev/null 2>&1; then
-                # find "$dir/$name" -type f -name '*.rar' | \
-                # while IFS= read -r file; do
-                    # dir=${file%/*}
-                    # unrar x -y -p- -o+ "$file"
-                # done
-                # [ 1 = "$VERBOSE" ] && echo "Unrarred $dir/$name"
-            # fi
-
-            continue
+            removed=1
+            [ 1 = "$VERBOSE" ] && printf "Removed idle torrent: $name\n"
+        elif [ 'Stopped' = "$state" ]; then
+            transmit --torrent "$id" --remove >/dev/null 2>&1
+            removed=1
+            [ 1 = "$VERBOSE" ] && printf "Removed completed torrent: $name\n"
         fi
     fi
+    if [ 1 = "$removed" ] && [ 1 = "$unrarred" ]; then
+        find "$dir/$name" -type f -name '*.rar' -o -name '*.r[0-9]' -o \
+            -name '*.r[0-9][0-9]' -o -name '*.r[0-9][0-9][0-9]' -o     \
+            -name '*.sfv' -o -name '*.nfo' -print0 | xargs -0 rm -f
+        [ 1 = "$VERBOSE" ] && printf "Removed RAR archives: $name\n"
+    fi
 
-    # TODO: treat demonoid.com as public
+    # TODO: treat demonoid.com tracker as public since ratios don't matter.
     if [ 'Yes' = "$public" ] && [ "$PUBLIC_UP_RATE" != "${up_rate%% *}" ]
     then
         transmit --torrent "$id" --torrent-uplimit "$PUBLIC_UP_RATE" \
             --seedratio "$PUBLIC_RATIO" >/dev/null 2>&1
-        [ 1 = "$VERBOSE" ] && echo "Throttled public torrent: $name"
+        [ 1 = "$VERBOSE" ] && printf "Throttled public torrent: $name\n"
     fi
 done
